function config = configuration(inputConfig)
%CONFIGURATION Return deterministic defaults with optional overrides.
% Focus thresholds use variance normalized by max(mean FOV intensity^2,
% 0.01), which prevents exposure from masquerading as defocus.

config = struct( ...
    'fovThreshold', 0.05, ...
    'minimumFovAreaRatio', 0.15, ...
    'centerOffsetLimit', 0.18, ...
    'darkPixelThreshold', 0.05, ...
    'saturationThreshold', 0.98, ...
    'illuminationSigma', 15, ...
    'fovAreaBorderline', 0.30, ...
    'laplacianUngradable', 1.0e-6, ...
    'laplacianBorderline', 1.0e-5, ...
    'tenengradUngradable', 1.0e-4, ...
    'tenengradBorderline', 5.0e-4, ...
    'meanDarkUngradable', 0.06, ...
    'meanDarkBorderline', 0.14, ...
    'darkFractionUngradable', 0.90, ...
    'darkFractionBorderline', 0.55, ...
    'saturatedFractionUngradable', 0.25, ...
    'saturatedFractionBorderline', 0.05, ...
    'rmsContrastUngradable', 0.01, ...
    'rmsContrastBorderline', 0.025, ...
    'entropyUngradable', 1.5, ...
    'entropyBorderline', 2.5, ...
    'illuminationCvUngradable', 0.45, ...
    'illuminationCvBorderline', 0.25, ...
    'denoiseDegree', 0.005, ...
    'enhancementEnabled', true, ...
    'claheEnabled', true);

if nargin == 0 || isempty(inputConfig)
    return;
end

if ischar(inputConfig) || (isstring(inputConfig) && isscalar(inputConfig))
    configFile = char(inputConfig);
    if ~isfile(configFile)
        error('quality:InvalidConfig', 'Configuration file does not exist: %s', configFile);
    end
    inputConfig = jsondecode(fileread(configFile));
end
if ~isstruct(inputConfig) || ~isscalar(inputConfig)
    error('quality:InvalidConfig', 'Configuration must be a scalar struct or JSON file.');
end
if isfield(inputConfig, 'quality')
    inputConfig = inputConfig.quality;
end
if ~isstruct(inputConfig) || ~isscalar(inputConfig)
    error('quality:InvalidConfig', 'The quality configuration must be a scalar struct.');
end

names = fieldnames(inputConfig);
for index = 1:numel(names)
    name = names{index};
    if isfield(config, name)
        value = inputConfig.(name);
        if islogical(value) && isscalar(value)
            config.(name) = value;
        elseif ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
            error('quality:InvalidConfig', ...
                'Quality configuration value %s must be a finite scalar.', name);
        else
            config.(name) = double(value);
        end
    end
end
end
