function modelPath = buildDistrictModel(forceRebuild)
%BUILDDISTRICTMODEL Build the native SimEvents district capacity model.

if nargin == 0
    forceRebuild = false;
end
modelPath = fullfile(fileparts(mfilename('fullpath')), 'district_model.slx');
modelName = 'district_model';
if isfile(modelPath) && ~forceRebuild
    return
end

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
load_system('sldelib');
add_block('simulink/User-Defined Functions/Simulink Function', ...
    [modelName '/timeStamp'], 'Position', [30 500 160 550]);
set_param([modelName '/timeStamp/f'], 'FunctionName', 'timeStamp');
timeStampInput = [modelName '/timeStamp/u'];
timeStampInputLine = get_param(timeStampInput, 'LineHandles');
if timeStampInputLine.Outport ~= -1
    delete_line(timeStampInputLine.Outport);
end
delete_block(timeStampInput);
add_block('simulink/Sources/Digital Clock', ...
    [modelName '/timeStamp/Digital Clock'], 'Position', [20 35 80 65], ...
    'SampleTime', '-1');
add_line([modelName '/timeStamp'], 'Digital Clock/1', 'y/1');

add_block('sldelib/Entity Generator', [modelName '/Entity Generator'], ...
    'Position', [30 80 160 130]);
add_block('sldelib/Entity Input Switch', [modelName '/PHC Capture Input Merge'], ...
    'Position', [175 70 205 140]);
add_block('sldelib/Entity Queue', [modelName '/PHC Capture Queue'], ...
    'Position', [210 80 330 130]);
add_block('sldelib/Entity Server', [modelName '/Capture Service'], ...
    'Position', [390 80 520 130]);
add_block('sldelib/Entity Server', [modelName '/Quality Assessment Service'], ...
    'Position', [580 220 730 270]);
add_block('sldelib/Entity Output Switch', [modelName '/Quality Gate Router'], ...
    'Position', [580 50 710 150]);
add_block('sldelib/Entity Server', [modelName '/Local AI Inference'], ...
    'Position', [790 80 930 130]);
add_block('sldelib/Entity Output Switch', [modelName '/Decision Router'], ...
    'Position', [990 50 1120 150]);
add_block('sldelib/Entity Input Switch', [modelName '/Upload Input Merge'], ...
    'Position', [1150 250 1260 350]);
add_block('sldelib/Entity Queue', [modelName '/Upload Queue'], ...
    'Position', [1300 270 1420 320]);
add_block('sldelib/Entity Server', [modelName '/Upload Service'], ...
    'Position', [1460 270 1590 320]);
add_block('sldelib/Entity Queue', [modelName '/Human Grader Review Queue'], ...
    'Position', [1630 270 1780 320]);
add_block('sldelib/Resource Pool', [modelName '/Grader Resource Pool'], ...
    'Position', [1600 410 1740 460]);
add_block('sldelib/Resource Acquirer', [modelName '/Acquire Grader'], ...
    'Position', [1820 270 1900 320]);
add_block('sldelib/Entity Server', [modelName '/Human Grader Service'], ...
    'Position', [1940 270 2070 320]);
add_block('sldelib/Resource Releaser', [modelName '/Release Grader'], ...
    'Position', [2110 270 2190 320]);
add_block('sldelib/Entity Terminator', [modelName '/Completed Report Output'], ...
    'Position', [2230 270 2340 320]);
add_block('sldelib/Entity Terminator', [modelName '/Auto Clear Output'], ...
    'Position', [1150 70 1260 120]);

set_param([modelName '/PHC Capture Input Merge'], ...
    'NumberInputPorts', '2', 'ActivePortSelection', 'All');
set_param([modelName '/Quality Gate Router'], ...
    'NumberOutputPorts', '3', ...
    'SwitchingCriterion', 'From attribute', ...
    'SwitchAttributeName', 'QualityRoute');
set_param([modelName '/Decision Router'], ...
    'NumberOutputPorts', '3', ...
    'SwitchingCriterion', 'From attribute', ...
    'SwitchAttributeName', 'DecisionRoute');
set_param([modelName '/Upload Input Merge'], ...
    'NumberInputPorts', '3', 'ActivePortSelection', 'All');

add_line(modelName, 'Entity Generator/1', 'PHC Capture Input Merge/1');
add_line(modelName, 'PHC Capture Input Merge/1', 'PHC Capture Queue/1');
add_line(modelName, 'PHC Capture Queue/1', 'Capture Service/1');
add_line(modelName, 'Capture Service/1', 'Quality Assessment Service/1');
add_line(modelName, 'Quality Assessment Service/1', 'Quality Gate Router/1');
add_line(modelName, 'Quality Gate Router/1', 'Local AI Inference/1');
add_line(modelName, 'Quality Gate Router/2', 'PHC Capture Input Merge/2');
add_line(modelName, 'Quality Gate Router/3', 'Upload Input Merge/3');
add_line(modelName, 'Local AI Inference/1', 'Decision Router/1');
add_line(modelName, 'Decision Router/1', 'Auto Clear Output/1');
add_line(modelName, 'Decision Router/2', 'Upload Input Merge/1');
add_line(modelName, 'Decision Router/3', 'Upload Input Merge/2');
add_line(modelName, 'Upload Input Merge/1', 'Upload Queue/1');
add_line(modelName, 'Upload Queue/1', 'Upload Service/1');
add_line(modelName, 'Upload Service/1', 'Human Grader Review Queue/1');
add_line(modelName, 'Human Grader Review Queue/1', 'Acquire Grader/1');
add_line(modelName, 'Acquire Grader/1', 'Human Grader Service/1');
add_line(modelName, 'Human Grader Service/1', 'Release Grader/1');
add_line(modelName, 'Release Grader/1', 'Completed Report Output/1');

set_param([modelName '/Entity Generator'], ...
    'GenerationMethod', 'Time-based', ...
    'TimeSource', 'MATLAB action', ...
    'GenerateEntityAtSimulationStart', 'off', ...
    'IntergenerationTimeAction', [ ...
    'coder.extrinsic(''districtNextArrival''); ' ...
    'dt = 0; ' ...
    'dt = double(districtNextArrival(districtArrivalRate, districtArrivalModeCode, districtCampBurstMultiplier));'], ...
    'GenerateAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'entity.ArrivalTime = timeStamp(); districtSimulationLog(''generated''); ' ...
    'entity.AttemptNumber = 0; entity.QualityRoute = 1; entity.DecisionRoute = 1;'], ...
    'EntityType', 'Structured', ...
    'EntityTypeName', 'Entity', ...
    'AttributeName', ...
    'PatientID|ArrivalTime|AttemptNumber|QualityFailed|QualityRoute|DecisionRoute', ...
    'AttributeInitialValue', '0|0|0|0|1|1');

set_param([modelName '/PHC Capture Queue'], ...
    'Capacity', 'inf', ...
    'EntryAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 1, 1, timeStamp());'], ...
    'ExitAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 1, -1, timeStamp());'], ...
    'NumberEntitiesInBlock', 'on');
set_param([modelName '/Capture Service'], ...
    'Capacity', 'districtNumberOfPHCs', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'districtCaptureTimeSeconds', ...
    'ServiceCompleteAction', [ ...
    'coder.extrinsic(''districtSimulationLog'', ''rand''); ' ...
    'entity.AttemptNumber = entity.AttemptNumber + 1; ' ...
    'qualityDraw = 0; qualityDraw = rand(1,1); ' ...
    'if districtQualityGateEnabled, entity.QualityFailed = double(qualityDraw < districtQualityRejectionRate); ' ...
    'else, entity.QualityFailed = 0; end; ' ...
    'if entity.QualityFailed && entity.AttemptNumber <= districtMaximumRecaptureAttempts, ' ...
    'entity.QualityRoute = 2; ' ...
    'elseif entity.QualityFailed, entity.QualityRoute = 3; ' ...
    'else, entity.QualityRoute = 1; end; ' ...
    'districtSimulationLog(''quality'', entity.QualityFailed, entity.AttemptNumber, districtMaximumRecaptureAttempts);']);
set_param([modelName '/Quality Assessment Service'], ...
    'Capacity', 'districtNumberOfPHCs', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'districtQualityGateTimeSeconds');
set_param([modelName '/Local AI Inference'], ...
    'Capacity', 'districtNumberOfPHCs', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'districtInferenceTimeSeconds', ...
    'ServiceCompleteAction', [ ...
    'coder.extrinsic(''districtSimulationLog'', ''rand''); ' ...
    'deferralDraw = 0; deferralDraw = rand(1,1); ' ...
    'prevalenceDraw = 0; prevalenceDraw = rand(1,1); ' ...
    'operatingDraw = 0; operatingDraw = rand(1,1); ' ...
    'if deferralDraw < districtDeferralRate, entity.DecisionRoute = 3; ' ...
    'else, hasDisease = prevalenceDraw < districtReferablePrevalence; ' ...
    'if hasDisease && operatingDraw < districtModelSensitivity, entity.DecisionRoute = 2; ' ...
    'elseif ~hasDisease && operatingDraw > districtModelSpecificity, entity.DecisionRoute = 2; ' ...
    'else, entity.DecisionRoute = 1; end; end; ' ...
    'districtSimulationLog(''decision'', entity.DecisionRoute);']);
set_param([modelName '/Upload Queue'], ...
    'Capacity', 'inf', ...
    'EntryAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 2, 1, timeStamp());'], ...
    'ExitAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 2, -1, timeStamp());'], ...
    'NumberEntitiesInBlock', 'on');
set_param([modelName '/Upload Service'], ...
    'Capacity', '1', ...
    'ServiceTimeSource', 'MATLAB action', ...
    'ServiceTimeAction', [ ...
    'tx = districtImageSizeMegabytes * 8 / districtBandwidthMegabitsPerSecond; ' ...
    'cycle = districtConnectivityCycleSeconds; ' ...
    'phase = mod(timeStamp(), cycle); ' ...
    'window = districtConnectivityAvailability * cycle; ' ...
    'if phase < window, dt = tx; else, dt = (cycle - phase) + tx; end;']);
set_param([modelName '/Human Grader Review Queue'], ...
    'Capacity', 'inf', ...
    'EntryAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 3, 1, timeStamp());'], ...
    'ExitAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'districtSimulationLog(''queue'', 3, -1, timeStamp());'], ...
    'NumberEntitiesInBlock', 'on');

set_param([modelName '/Grader Resource Pool'], ...
    'ResourceName', 'Graders', ...
    'ReusableUponRelease', 'on', ...
    'ResourceAmountSource', 'Dialog', ...
    'ResourceAmount', 'districtNumberOfGraders', ...
    'AverageUtilization', 'on', 'AmountInUse', 'on');
set_param([modelName '/Acquire Grader'], ...
    'ResourceName', 'Graders', ...
    'ResourceAmountSource', 'Dialog', ...
    'ResourceAmount', '1');
set_param([modelName '/Human Grader Service'], ...
    'Capacity', '1', ...
    'ServiceTimeSource', 'Dialog', ...
    'ServiceTimeValue', 'districtGraderServiceTimeSeconds', ...
    'ServiceCompleteAction', [ ...
    'coder.extrinsic(''districtSimulationLog''); ' ...
    'now = timeStamp(); ' ...
    'districtSimulationLog(''completed'', now - entity.ArrivalTime, districtGraderServiceTimeSeconds);'], ...
    'Utilization', 'on');
set_param([modelName '/Completed Report Output'], 'NumberEntitiesArrived', 'on');
set_param([modelName '/Auto Clear Output'], 'NumberEntitiesArrived', 'on');

set_param(modelName, 'StopTime', 'districtSimulationDurationDays * 86400');
set_param(modelName, 'SaveOutput', 'off', 'SignalLogging', 'off');
save_system(modelName, modelPath);
close_system(modelName, 0);
end
