function evidence = icdrEvidenceFromDetection(detection)
%ICDREVIDENCEFROMDETECTION Build ICDR evidence from classical detection.
%   EVIDENCE = grade.icdrEvidenceFromDetection(DETECTION) turns the output
%   of segment.detect into the structured evidence grade.icdrRule consumes,
%   and declares which of the eight evidence fields a detector in this build
%   is actually responsible for.
%
%   Only classical microaneurysm candidate detection exists, so the other
%   seven fields are unknown on every image.  That is a capability gap, not
%   a fact about any particular patient, and the declaration is what lets
%   grade.icdrRule tell the two apart.  Without it every image looks like a
%   case with missing evidence and the decision layer escalates all of them.
%
%   This lives here rather than in each caller because app.runScreeningCase
%   and eval/ablationHarness.m both need it and must not drift: the
%   ablation measures the deployed pipeline only while the two agree, and
%   they previously held separate copies of this construction.

candidateCount = double(detection.candidateCount);
unknownCount = struct('value', [], 'known', false);
unknownVector = struct('value', [], 'known', false);
unknownLogical = struct('value', [], 'known', false);
coverage = struct( ...
    'microaneurysmCount', true, ...
    'haemorrhageCountPerQuadrant', false, ...
    'hardExudateCount', false, ...
    'softExudateCount', false, ...
    'venousBeadingPerQuadrant', false, ...
    'irmaPerQuadrant', false, ...
    'neovascularisation', false, ...
    'vitreousOrPreretinalHaemorrhage', false);
evidence = struct( ...
    'microaneurysmCount', struct('value', candidateCount, 'known', true), ...
    'haemorrhageCountPerQuadrant', unknownVector, ...
    'hardExudateCount', unknownCount, ...
    'softExudateCount', unknownCount, ...
    'venousBeadingPerQuadrant', unknownLogical, ...
    'irmaPerQuadrant', unknownLogical, ...
    'neovascularisation', unknownLogical, ...
    'vitreousOrPreretinalHaemorrhage', unknownLogical, ...
    'evidenceFieldCoverage', coverage, ...
    'evidenceSource', 'classical candidate evidence', ...
    'clinicalValidationStatus', 'not clinically validated lesion segmentation');
end
